CREATE TABLE IF NOT EXISTS CUSTOMER(
ID INT AUTO_INCREMENT  PRIMARY KEY,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR (100) NOT NULL,
ADDRESS VARCHAR (200) NOT NULL,
CITY VARCHAR (100) NOT NULL,
PHONENUMBER VARCHAR (100),
EMAIL VARCHAR (100),
COURSE VARCHAR (100) NOT NULL,
INSCRIPTIONDATE DATE NOT NULL
);